### ISSUE TITLE
Almost-identical KDE/Plasma 'metadata' files shipped upstream and downstream

### ISSUE THREAD

**Issue by AdamWill** [fedoradesign/backgrounds#16]
So, this seems pretty bizarre. In this ('upstream') repo we have the file `default/fXX-metadata.desktop` - currently https://github.com/fedoradesign/backgrounds/blob/master/default/f31-metadata.desktop . In the 'downstream' package repository we have an almost-identical `fXX-metadata.desktop` file - currently https://src.fedoraproject.org/rpms/f31-backgrounds/blob/master/f/f31-metadata.desktop . They are nearly the same, except the section names in the downstream file all start with `X-` while the ones in the upstream file don't.

In the end, both files wind up in the `f31-backgrounds-kde` package, but in different places. The 'upstream' file winds up as `/usr/share/wallpapers/F31/metadata.desktop`. The `downstream` file winds up as `/usr/share/plasma/desktoptheme/F31/metadata.desktop`. This of course means we have twice as many chances to get something wrong when bumping from release to release, as someone has to remember to change all the numbers in *both* files.

Why are things like this? This seems bad. :)

**Comment by luyatshimbalanga** [comment]
The use of "X-" was a [leftover from the review process](https://bugzilla.redhat.com/show_bug.cgi?id=1745846#c13) requiring the use of desktop-file-utils for validation . I forgot to remove these prefix downstream after importing the SRPM.

Before making a full change here upstream, is the "/usr/share/wallpapers/" path still valid for KDE or "/usr/share/plasma/desktoptheme/"?

**Comment by rdieter** [comment]
both paths are valid, depending on the context.
/usr/share/wallpapers are for backgrounds
/usr/share/plasma/desktopthemes are for plasma themes

Using desktop-file-validate in this context is not valid, this isn't an application .desktop file.  (Yes, kde kinda abuses .desktop files for other purposes, but doesn't mean it's *wrong*.

**Comment by AdamWill** [comment]
I mean, if you're calling it a `.desktop` file it should follow the spec for `.desktop` files :P I [filed a bug](https://bugs.kde.org/show_bug.cgi?id=411876).

I'm fixing the package to drop the downstream copy of the metadata file and just install the upstream copy to the other location, but ultimately shouldn't we fix the upstream tarball to install the file to both locations and not have the package do it?

Also, just to be really clear, @rdieter , do we really need to drop this identical `metadata.desktop` file in both locations?

**Comment by luyatshimbalanga** [comment]
Thank you @rdieter about wallpapers and desktoptheme path for KDE. 
@AdamWill  Based on the comments, we dropped the downstream metadata.desktop in favour of upstream instead. The change is already applied  on the [makefile](https://github.com/fedoradesign/backgrounds/commit/32f82fbf6eadbfb57e6a00e4986be45f76c34ce3) and will be release as soon as possible.

**Comment by luyatshimbalanga** [comment]
A new tarball addressing the issue related to metadata.desktop is now available. The package version is released on both [Rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=37656855) and [Fedora 31 repository](https://koji.fedoraproject.org/koji/taskinfo?taskID=37656858). 
Closing this report as fixed.
