### ISSUE TITLE
missing symlink /usr/share/backgrounds/default.xml

### ISSUE THREAD

**Issue by raveit65** [fedoradesign/backgrounds#20]
Can you please add a symlink `/usr/share/backgrounds/default.xml`
which links to `/usr/share/backgrounds/f32/default/f32.xml`
```
ln -s /usr/share/backgrounds/f32/default/f32.xml /usr/share/backgrounds/default.xml 
```
MATE desktop use a gsettings key to define the default fedora background.
```
[org.mate.background]
picture-filename='/usr/share/backgrounds/f32/default/f32.xml'
```
As you can see because of the `f32` in directory i have to update every release the gesetting key to match the new default background.
For this reason the mate-compiz f32 spin will use the f31 background, because we are in beta freeze.
So, adding a symlink `/usr/share/backgrounds/default.xml` without a fedora release number would help me a lot. In result i don't have to edit the gsettings key every release.
I am sure that is helpful for other desktops too.

Thank you

**Comment by luyatshimbalanga** [comment]
Or even better,
`ln -s /usr/share/backgrounds/f32/default/f32.xml /usr/share/backgrounds/mate/default.xml `
because the fix is specificf or MATE in this case. Note the "mate" folder.

**Comment by raveit65** [comment]
Thanks a lot.
Is it possible to build a new RPM for fedora with this fix, please?

**Comment by luyatshimbalanga** [comment]
The fix should be in place on the recent release. Closing.
