### ISSUE TITLE
fedora-backgrounds-32.1.4: broken symlinks

### ISSUE THREAD

**Issue by pacho2** [fedoradesign/backgrounds#22]
Hello,

When installing this new version I get links in /usr/share/wallpapers/F32/contents/images/ pointing to nothing. It seems they point to ../../backgrounds/f32/default/f32.png , but f32.png is installed under two levels upper -> ../../../../backgrounds/

Thanks

**Comment by luyatshimbalanga** [comment]
Hello pacho2,
Thanks for finding a bug. The fix is now available at the same version. You will need to download again to get the update. 
https://github.com/fedoradesign/backgrounds/releases/tag/v32.1.4

**Comment by pacho2** [comment]
It works

Thanks
