### ISSUE TITLE
Animated wallpaper bug or feature?

### ISSUE THREAD

**Issue by maxborowsky** [fedoradesign/backgrounds#26]
Update 32.2.2 fixed the problem with missing wallpaper by default, thanks. But now you can see not only the F32 animated wallpaper, but also separately dawn, day etc. Is it not more appropriate to do as in Adwaita animated wallpaper, when only the choice of animation itself is visible, but not its frames separately?
![Screenshot from 2020-05-06 16-23-50](https://user-images.githubusercontent.com/20723033/81182977-389fb800-8fb7-11ea-8196-4df7f4ab70a5.png)

**Comment by luyatshimbalanga** [comment]
It is an experimental feature in this case on Fedora 32. For the next release I may set the animate wallpaper as default without its separate frame.

**Comment by maxborowsky** [comment]
@luyatshimbalanga, do you mean in the next release of Fedora or in the next release of this package?

**Comment by luyatshimbalanga** [comment]
Both
