### ISSUE TITLE
Star movement in F33 animated background: intentional?

### ISSUE THREAD

**Issue by AdamWill** [fedoradesign/backgrounds#28]
In the current version of the F33 backgrounds, the starfield moves. In night and dawn it's more to the left, in day and dusk it's more to the right. This leads to an odd effect during the transitions, where the starfield kinda fades out at one location and fades in at the other. In the middle of the transition it's sort of duplicated with each one being very faded, like this:

![dupestars](https://user-images.githubusercontent.com/916551/95496538-ded05f00-0955-11eb-9c98-0e87125b7d96.png)

is this intentional, or an oversight?

**Comment by luyatshimbalanga** [comment]
@AdamWill 
It is an accidental oversight. It seems subtle but no enough to impact the productivity. We can leave as it is.
