### ISSUE TITLE
wget link in the readme is broken

### ISSUE THREAD

**Issue by stardude900** [fedoradesign/backgrounds#31]
The readme says to wget https://github.com/fedoradesign/backgrounds/releases/download/v35.0.1/f35-backgrounds-35.0.1-1.f35.src.rpm, but that link returns 404

**Comment by luyatshimbalanga** [comment]
Thanks for pointing out. Fedora 35 default wallpaper is not ready yet. To avoid confusion, the readme is reverted to Fedora 34 version. Once ready, the link will be functional.
