### ISSUE TITLE
Opinion about the background

### ISSUE THREAD

**Issue by DEM0NAssissan7** [fedoradesign/backgrounds#32]
**Disclaimer: This is all my personal opinion.**

I feel that the current background for F35 is not very deep and it's too chaotic and strange to be a Fedora background. The colors and patterns seem off, and the coloring and lighting do not match with the look of the rest of the Fedora Project or with any of the previous backgrounds. I understand the need to innovate with new backgrounds, but all the backgrounds should still follow the same simple philosophy: simple, deep, and impactful.

I think that the pattern that the background adopts is too chaotic and strange. The pattern that the background follows is too curvy as well. It does not look orderly or simplistic whatsoever. The backgrounds that have been in other Fedora releases have always been simple and deep. Fedora backgrounds typically follow a very simple pattern that is then expanded and given depth and color. This background simply looks like someone went into GIMP, rendered a random fractal from the preset fractals, applied some color work, and called it a day. It does not look like deep, stunning, or impressive. 

The TL;DR is that the current background is an eyesore to look at.

To fix it, I suggest taking inspiration from other Fedora releases. Also, at **[the pagure page for the background](https://pagure.io/design/issue/707)**, there are some amazing backgrounds that don't have anything to do with the strange 'fractal' look. Two of the backgrounds that have caught my attention are [this concept art made by _riecatnor_](https://pagure.io/design/issue/raw/files/7e6f004bf9d7e78004c7aeb16041855d6b177fd8f949202ca7759771f696a3f0-F35_wallpaper_drawing.png) and [this render](https://pagure.io/design/issue/raw/files/2066e6e3886f5840893f2ec869817a225f7101ca48f03430a22a854270477d9b-f35-modification.png).

If using an alternate background style is not viable, I suggest making the background darker and more blue or to use a more complicated render like [this one](https://pagure.io/design/issue/raw/files/fdd6eadea4c23955e6e9a8abbcaaa32a60393c93ec038bfb4fa0f1a4db06f154-IMG_5578.JPG). I would also suggest looking at [this concept art on pagure](https://pagure.io/design/issue/raw/files/3387f5d5598ac3407a202eff028b94ddc7c415b9b72f47737bf94e503c1cc65a-marie-f35-mod.png). 

All of these pieces of art share the same qualities: geometric patterns, deep colors and depths, and stunning visuals.

This is simply a suggestion and a complaint about the current background of Fedora 35. I understand if it may be too late to reconsider other background options, or if the team has already chosen this background for some mystical, wise reason. Please consider my suggestions to fix the current background

Thank you for your time!

**Comment by mairin** [comment]
Hi @DEM0NAssissan7 - thanks for the thoughtful feedback! I am taking a look today to see what I can do to iterate the wallpaper or swap for one of the ones from the conceptual process that you liked. Stay tuned :)

**Comment by mairin** [comment]
@DEM0NAssissan7 

Current:

![f35-01-day opti sm](https://user-images.githubusercontent.com/799683/134061123-75d14f2e-4d8f-489d-a0dc-d31b09617390.png)

With tweaks:

![E_wIVuBUUAkpYf7](https://user-images.githubusercontent.com/799683/134062689-48d91b60-01e7-4ae8-8fd3-c8f1cb4d9c15.jpg)


(Note these are cropped and the first is scaled down bc of GitHub's image size limit. Sigh.)

**Comment by mairin** [comment]
Quick update based on feedback. :) I'm going to point you to the tweet with the update because of GitHub's oppressive image size limits!

https://twitter.com/mairin/status/1440053651104432134

**Comment by DEM0NAssissan7** [comment]
This is actually really good! I am quite impressed with how a little lighting change can go a long way.

I made my own color corrections to the images uploaded on twitter. I honestly have no idea what I did but let me know what you think! Hopefully my mediocre color correction skills will be enough to make this into the final release.

![fedora35_background_day_EXP](https://user-images.githubusercontent.com/42104518/134128186-ffe8bde1-7621-4a7a-822d-fcf0e8c6ab04.jpg)
![fedora35_background_night_EXP](https://user-images.githubusercontent.com/42104518/134128204-158d1694-dd64-46a9-8b15-bf8b10ab1a72.jpg)

**Comment by mairin** [comment]
@DEM0NAssissan7 Hey I like where you got those! Can you help me understand what workflow & tools you used? (The twitter versions are heavily compressed so I'd need to recreate on the full quality sources)

**Comment by DEM0NAssissan7** [comment]
So, I honestly have no idea what I did to make it that color. I just went into GIMP, loaded up the image, applied some value & color level tweaks (using the color tab), and did some color mixing settings to make sure nothing stood out too much. I also messed with the brightness and contrast. I also messed around with color curves (just for fun). Took me about 45 minutes to complete both images, including testing and all.

**Comment by DEM0NAssissan7** [comment]
I'm going to work on getting the raw image files and applying the color work i did to the compressed one. I'll update in a little bit when I get it done. I will also record all of the work that I do so that we can replicate/tweak it later. 

_Also, @mairin can you please email me a copy of the raw image files. Email is abdurahman.elmawi06@gmail.com. Thanks!_

Edit: I got the original image files from the tag with F35. You don't need to send me anything.

**Comment by DEM0NAssissan7** [comment]
Okay! Just did some color work with the original images. I messed around with colors, contrast, value, and a whole bunch of other stuff. Let me know what you think!

Keep in mind that these images do not have the blurring or coloring effects that were done on twitter. These are before that.
I'll send a google drive link (because Github).

[Google Drive Link (with both day and night)](https://drive.google.com/drive/folders/1Zua9ET7_OQsUe1F5z-Mm6GAvX4ZB5dvV?usp=sharing)

**Comment by mairin** [comment]
@DEM0NAssissan7 thanks for all of your feedback! This is what we ended up with:
https://pagure.io/design/issue/707#comment-753829

I am going to close this ticket because it seems like we addressed the concerns you had.
