### ISSUE TITLE
f35-backgrounds-35.0.1 installs broken symlink

### ISSUE THREAD

**Issue by pacho2** [fedoradesign/backgrounds#33]
Symbolic link /usr/share/xfce4/backdrops/f35-dark-blue.png points to /usr/share/xfce4/backgrounds/f35/extras/dark-blue.png which does not exist.

Thanks a lot for fixing it!

**Comment by pacho2** [comment]
The same happens with 36.0.1

**Comment by luyatshimbalanga** [comment]
Does the new version resolve the issue? I don't have XFCE installed in my system.

**Comment by pacho2** [comment]
fixed in latest version, thanks!
