### ISSUE TITLE
f36-backgrounds doesn't display correctly

### ISSUE THREAD

**Issue by gspe** [fedoradesign/backgrounds#38]
I'm currently using Fedora Silverblue 36 and after some updates the background doesn't display correctly.
Here some images 
![Screenshot from 2022-04-27 12-59-46](https://user-images.githubusercontent.com/883731/165506282-cba8dbec-5cff-4235-8602-af8e2ff5d5b2.png)
![Screenshot from 2022-04-27 13-05-19](https://user-images.githubusercontent.com/883731/165506288-276f9ab0-0f7e-4d5e-8732-561fcf72bbbf.png)

**Comment by luyatshimbalanga** [comment]
Hello, it looks like the display is roughly 21:9 causing the background to zoom in. It is an expected behaviour to avoid stretching it.
Switch to another background with the similar dimension to see it is a non-issue per se.

**Comment by gspe** [comment]
The display has a resolution of 3840x1600.

It's a pity that this background doesn't works with my screen resolution, the default background of Fedora 35 and 34 worked well on this resolution.

**Comment by luyatshimbalanga** [comment]
In a future, we will take account of wider screen. 
As a work around, set `<options>zoom</options>` to `<options>stretch</options>` inside ``/usr/share/gnome-background-properties/f36.xml``. Also tried the following options: "wallpaper", "centered", "scaled"

**Comment by bkmgit** [comment]
@gspe Can you test f37 versions?

**Comment by gspe** [comment]
@bkmgit  Sorry for late answer, I was on holidays.

I've rebased  my f36 silverblue to f37 and the background seams to display correctly

**Comment by luyatshimbalanga** [comment]
Let's make the issue as resolved. Should the issue occur again, feel free to reopen.
