### ISSUE TITLE
Time of Day background does not appear in gnome settings

### ISSUE THREAD

**Issue by TitanNano** [fedoradesign/backgrounds#44]
The "Time of Day" version of the F37 background does not show up in gnome settings, only the light/dark version.

I believe this is caused by it not being part of [`gnome-backgrounds-f37.xml`](https://github.com/fedoradesign/backgrounds/blob/0815aa07b802e91f22354b04fdbeb2c0b0081415/default/gnome-backgrounds-f37.xml). Looking at [`gnome-backgrounds-f36.xml`](https://github.com/fedoradesign/backgrounds/blob/960d1d64941940ef3a9116e41664acfac69dea78/default/gnome-backgrounds-f36.xml) I can see that the last wallpaper defined two versions.

**Comment by luyatshimbalanga** [comment]
Hello,
the fix is in place on [37.0.5](https://github.com/fedoradesign/backgrounds/releases/tag/v37.0.5).
