### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by xsuchy** [fedoradesign/backgrounds#46]
As part of https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
I wanted to check what SPDX string will be for this package. Currently, the spec file uses: CC-BY-SA. Which is ambiguous:
```
 $ license-fedora2spdx 'CC-BY-SA'
Warning: more options on how to interpret CC-BY-SA. Possible options: ['CC-BY-SA-4.0', 'CC-BY-SA-3.0', 'CC-BY-SA-3.0-DE', 'CC-BY-SA-3.0-AT', 'CC-BY-SA-2.5', 'CC-BY-SA-2.1-JP', 'CC-BY-SA-2.0', 'CC-BY-SA-2.0-UK', 'CC-BY-SA-1.0']
{{pick CC-BY-SA choice}}
```
Looking at this project and the code - it seems that the correct one will be 'CC-BY-SA-4.0'. But I am puzzled by the presence of:
* [CC-BY-4.0](https://github.com/fedoradesign/backgrounds/blob/main/CC-BY-4.0)
* [CC0-1.0](https://github.com/fedoradesign/backgrounds/blob/main/CC0-1.0)
* [Free-Art-1.3](https://github.com/fedoradesign/backgrounds/blob/main/Free-Art-1.3)

Is anything licensed under this license? If not, should these files be present here? If yes, should the license be changed?

**Comment by luyatshimbalanga** [comment]
> Looking at this project and the code - it seems that the correct one will be 'CC-BY-SA-4.0'. But I am puzzled by the presence of:
> 
>     * [CC-BY-4.0](https://github.com/fedoradesign/backgrounds/blob/main/CC-BY-4.0)
> 
>     * [CC0-1.0](https://github.com/fedoradesign/backgrounds/blob/main/CC0-1.0)
> 
>     * [Free-Art-1.3](https://github.com/fedoradesign/backgrounds/blob/main/Free-Art-1.3)
> 
> 
> Is anything licensed under this license? If not, should these files be present here? If yes, should the license be changed?

Those licenses were for the supplemental wallpapers in extra sub-packages. They can be ignored as I will remove them from the branch to avoid confusion.

**Comment by luyatshimbalanga** [comment]
Closing as resolved.
