### ISSUE TITLE
gnome-backgrounds-f38 references non-existent webp files

### ISSUE THREAD

**Issue by felipeborges** [fedoradesign/backgrounds#48]
I suppose there was a move from webp to png and the https://github.com/fedoradesign/backgrounds/blob/main/default/gnome-backgrounds-f38.xml file didn't get updated.

In my F38 system I can find the .png files on those paths, but not the webp ones.

This was initially reported upstream in GNOME Settings https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2398

**Comment by kparal** [comment]
Downstream Fedora report:
https://bugzilla.redhat.com/show_bug.cgi?id=2178172

**Comment by luyatshimbalanga** [comment]
The fix is available and packaged on Fedora 38 repository.
