### ISSUE TITLE
F38 Default Dark does not show up in Budgie Control Center

### ISSUE THREAD

**Issue by JoshStrobl** [fedoradesign/backgrounds#50]
In Budgie Control Center, the night wallpaper does not show up as it is listed as `filename-dark` (presumably for GNOME Control Center's light vs dark selection) rather than having a dedicated wallpaper entry in the `gnome-backgrounds-f38.xml`

Could we either:

1. Get it added as a wallpaper entry in `gnome-backgrounds-f38.xml` so it shows up separately
2. Alternatively have a `f38-backgrounds-budgie` that installs an `f38-budgie.xml` in `/usr/share/gnome-background-properties` that has the dark image. This would depend on f38-backgrounds-gnome to pull in the "day" image as well.

I'd be open to providing a PR to add either option, I just imagine someone else would be doing the release + package update that includes the desired subpackage.

Doing either will be beneficial to the Fedora Budgie Spin. The night wallpaper could then be selected by the end user and I could do the work of updating budgie-desktop-defaults to have a f38 subpackage that requires the f38-backgrounds-budgie and sets the night backgrounds as the default (which ties in well with defaulting to dark theme). Otherwise I'll just be shipping  F38 Budgie Spin with a wallpaper from budgie-backgrounds (which is the current situation).

**Comment by luyatshimbalanga** [comment]
Hello Josh, feel free to set up a PR for f38-backgrounds-budgie.

**Comment by JoshStrobl** [comment]
@luyatshimbalanga So is the second option of having the dedicated file for budgie the preferred option? Just want to make sure we're on the same page before I work on a PR :)

**Comment by luyatshimbalanga** [comment]
@JoshStrobl  Yes, that second option so maintenance will be easier in the future.

**Comment by luyatshimbalanga** [comment]
Hello @JoshStrobl , any progress about the f38-backgrounds-budgie?

**Comment by luyatshimbalanga** [comment]
Hello @JoshStrobl, I created a subpackage for Budgie allowing to set night wallpaper as default. I took option 2 where you can choose f38-budgie.xml. I am closing this ticket as solved and feel free to reopen should that issue occur.
