### ISSUE TITLE
Time-based transition is broken

### ISSUE THREAD

**Issue by mcatanzaro** [fedoradesign/backgrounds#51]
At 6:03 PM today, using the time-based version of Fedora 38's default wallpaper, my wallpaper abruptly transitioned from light to almost pure dark. I thought it was a GNOME bug until I noticed that if you look really closely, you can see very faint clouds and dots:

![Screenshot from 2023-03-26 18-06-46](https://user-images.githubusercontent.com/1424966/227810600-d6c9c94e-83d1-4101-b772-cebd7603b1a4.png)

Hopefully there's an obvious problem with the animation. If not, I'd recommend removing the time-based version.

**Comment by luyatshimbalanga** [comment]
The issue is a three years old [unresolved GNOME bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1762) with 32-bits PNG wallpaper. Normally, upstream should address that is problem but the workaround is to convert to 24-bit PNG.

**Comment by luyatshimbalanga** [comment]
@mcatanzaro, can you test [this update](https://bodhi.fedoraproject.org/updates/FEDORA-2023-0cd43662e3)?

**Comment by mcatanzaro** [comment]
I've installed the update and switched back to the time-based wallpaper. Let's see if it breaks again. No news is good news....

**Comment by luyatshimbalanga** [comment]
Marking this ticket as solved!
