### ISSUE TITLE
Incorrect filename in the 40.1.1 release

### ISSUE THREAD

**Issue by database64128** [fedoradesign/backgrounds#63]
Hi, I maintain AUR packages for this repo. In the latest [40.1.1 release](https://github.com/fedoradesign/backgrounds/releases/tag/v40.1.1), the filename of the .tar.xz archive incorrectly states 40.1.0, and the rpm package is missing. Can we get this fixed so the packages I maintain can be updated? Thanks.

**Comment by luyatshimbalanga** [comment]
Hi @database64128 , thanks for catching the mistake. The correct tar.xz and the missing rpm packages are now applied on [40.1.1 release](https://github.com/fedoradesign/backgrounds/releases/tag/v40.1.1),
